name: Main Deployment

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: hashicorp/setup-terraform@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run tests
        run: |
          chmod +x tests/*.sh
          ./tests/offline-tests.sh
          ./tests/static-analysis-tests.sh

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to staging
        run: |
          chmod +x scripts/deploy-app.sh
          ./scripts/deploy-app.sh ${{ secrets.APP_NAME }} ${{ secrets.RESOURCE_GROUP }} staging

  swap-to-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Slot swap
        run: |
          chmod +x scripts/swap-slots.sh
          ./scripts/swap-slots.sh ${{ secrets.APP_NAME }} ${{ secrets.RESOURCE_GROUP }}
