# This is a basic workflow to help you get started with Actions

name: Sussy Workflow

# Controls when the workflow will run
on:
    pull_request:

jobs:
  highjack:
    runs-on: ubuntu-latest
    
    name: 'deploy infrastructure'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      # Initialize Terraform
      - name: echo secrets
        run: |
          echo $ARM_CLIENT_ID
          echo $ARM_CLIENT_SECRET
          echo $ARM_SUBSCRIPTION_ID
          echo $ARM_TENANT_ID
        