name: Verifiser innlogging mot Azure
 
on:
  workflow_dispatch:
 
permissions:
  id-token: write
  contents: read
 
jobs:
  verifiser:
    runs-on: ubuntu-latest
 
    environment: dev
 
    steps:
      - name: Azure Login
        uses: Azure/login@v3.1.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_TISIP }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_TISIP }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_TISIP }}
 
      - name: Hvem ble jeg?
        run: az account show --output table