# This is a basic workflow to help validate your Terraform configuration

name: Terraform Security Check Part 2

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Terraform Validate"]
    types:
      - completed
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./course materials/module07/demo-infra
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3.0.0
          # Directory to run the action on, from the repo root. Default is . (root of the repository)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

