# This is a basic workflow to help validate your Terraform configuration

name: Terraform Security Check Part 2

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Terraform Validate"]
    types:
      - completed
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Security Check"
  terraform:
    name: 'Security Check Part 2'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./course materials/module07/demo-infra
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run tfsec PR commenter
        # You may pin to the exact commit or the version.
        # uses: aquasecurity/tfsec-pr-commenter-action@7a44c5dcde5dfab737363e391800629e27b6376b
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          working_directory: ${{ env.WORKING_DIR }}    

